### ISSUE TITLE
Disbable Wiki

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-project-vulnerable-web-applications-directory#1]
Someone should disable the wiki (and perhaps projects), they're unlikely to be used. I had requested admin access but don't seem to have been granted it. @psiinon or @raulsiles perhaps you could approve that with @hblankenship for me?

**Comment by psiinon** [comment]
Weird - looks like you have admin access to me :/
I've just disabled the wiki.

**Comment by kingthorin** [comment]
Thanks @psiinon, I could go to settings and see you three as admin but not see that I was admin (may be a UI issue?). Also in settings I didn't see "Features" in order to disable the wiki :(

**Comment by psiinon** [comment]
You show up as an admin for me but not an Organisation member - maybe thats the problem?
I dont think I have perms to add you :/

**Comment by raulsiles** [comment]
I can see you both as Admins and Org Members now. I guess you cannot see yourself as Admin, as no profile button is displayed.
