### ISSUE TITLE
outdated link

### ISSUE THREAD

**Issue by mark-pictor-csec** [OWASP/www-project-vulnerable-web-applications-directory#131]
the web page
https://owasp.org/www-project-vulnerable-web-applications-directory/
has a link 
> The associated GitHub repository is available [here](https://github.com/OWASP/OWASP-VWAD).

(links to https://github.com/OWASP/OWASP-VWAD)
but that repo's description redirects here

**Comment by mark-pictor-csec** [comment]
Oops, I misread when the repos were last modified - I thought the migration had happened months ago, rather than being ongoing.

**Comment by kingthorin** [comment]
Good catch thanks I'll get that tweaked
